inherit: true

tools:
    php_code_sniffer: true
    php_cpd: false
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

    php_code_coverage:
      enabled: true
      test_command: phpunit --colors --verbose

filter:
    excluded_paths: ["lib/*"]

build_failure_conditions:
    - 'elements.rating(<= F).new.exists'
    - 'issues.severity(>= MAJOR).new.exists'