language: php

php:
  - 5.5
  - 5.6
  
matrix:
  allow_failures:
    - php: 5.6
    
sudo: false

git:
  submodules: true

before_script:
  - cd sql
  - ./create_db.sh
  - cd ..

script:
  - bash .travis.phplint.sh
  - phpunit

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikipedia-en-accounts-devs"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
